name: Tests

on: [push, pull_request]

jobs:
    call-tests:
        name: Extension tests
        uses: phpbb-extensions/test-framework/.github/workflows/tests.yml@master
        with:
            EXTNAME: vse/dbtool  # Your extension vendor/package name
            CODECOV: 1           # Run code coverage via codecov? 1 or 0
            RUN_PGSQL_JOBS: 0
            RUN_MSSQL_JOBS: 0
            RUN_WINDOWS_JOBS: 0
        secrets:
            CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} # Do not change this
